import type { Metadata } from 'next';
import { quicksand } from '@/app/components/ui/fonts';
import './globals.css';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${quicksand.className} antialiased`}
            >
                <div className="
                    container 
                    bg-white 
                    text-gray-900 
                    dark:bg-gray-800 
                    dark:text-white 
                    border-solid 
                    border-blue-300
                    w-auto
                    min-w-5/20
                    max-w-19/20
                    mt-5
                    mx-auto
                    p-6
                    box-border
                    shadow-2xl
                    rounded-2xl
                ">
                    {children}
                </div>
            </body>
        </html>
    );
}
